[server]
enableOIDC = true

[oidc]
client_id = "your-client-id-from-provider"
client_secret = "your-client-secret"
metadata_url = "https://your-oidc-provider/.well-known/openid-configuration"
redirect_uri = "http://localhost:8501" 